### ISSUE TITLE
Analyzer 5+ support

### ISSUE THREAD

**Issue by lcdsmao** [mj-hd/flutter_hooks_lint_plugin#25]
Analyzer 5+ is supported by analyzer_plugin 0.11.2.
But analyzer_plugin 0.11.0 introduced a lot of breaking changes.
I tried the migration but lacked some knowledge.

Reference: https://github.com/dart-code-checker/dart-code-metrics/pull/1020/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25

**Comment by mj-hd** [comment]
Ok, I will take a look.

**Comment by mj-hd** [comment]
@lcdsmao I've published https://pub.dev/packages/flutter_hooks_lint_plugin/changelog#060.
